name: ecom
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/chipped/
    - assets/images/laceration/
    - assets/images/broken_jaw/
    - assets/images/tooth_displaced/
    - assets/images/tooth_out_of_the_socket/

  uses-material-design: true
